### ISSUE TITLE
Should the host PC be Cuda enabled ?

### ISSUE THREAD

**Issue by l4es** [zhj-buffer/Cross-Compile-Jetson#2]
Hi,

I plan to do a setup like this for "cross development" and I'd like to know if it is necessary that the host PC has Nvidia Graphical Card for question of compatibility, please ?

Thanks in advance,
Pascal

**Comment by bradmccormack** [comment]
@FXRer I have only just looked at this repo. You don't need a compatible NVIDIA card on the host.

It's compiling to an ARM binary that runs in the NVIDIA hardware using compilers that run on x86 that produce ARM code.

You only need NVIDIA hardware if you are running the the Cuda code. If you chroot into a virtual-like environment to simulate the NVIDIA Jetson hardware you would still need to pass through the Nvidia host GPU to emulate Jetson Cuda code on the host.

The short answer should be "no"

**Comment by zhj-buffer** [comment]
Thanks bradmccormack for your reply.

Compiling only need the static libs/includes/sources/toolchains. When the code is runing, it should be transformed to assembler instruction which exactly need the target hardware(jetson).
