### ISSUE TITLE
apt-get hanging inside of chroot

### ISSUE THREAD

**Issue by Meatwad650** [zhj-buffer/Cross-Compile-Jetson#4]
I've followed along, but when I do an "apt-get upgrade" or "apt-get install" inside of the chroot it just hangs.  It downloads the package fine, but it just then hangs.  Any ideas what I might be doing wrong?

**Comment by zhj-buffer** [comment]
Are there any error hints during the mounting?
Could you share the errors?

**Comment by zhj-buffer** [comment]
Are there any error hints during the mounting?
Could you share the errors?

**Comment by jamesthesken** [comment]
I'm finding the same error too, I don't have any errors while mounting the image though.

At Step 3 of the tutorial, the packages load then it hangs on:
```
9 upgraded, 20 newly installed, 0 to remove and 254 not upgraded.
Need to get 0 B/66.1 MB of archives.
After this operation, 153 MB of additional disk space will be used.
```

Thank you for any guidance!

**Comment by zhj-buffer** [comment]
Are you able to access the network? 

sudo mount -o bind /run run

also rm /etc/resolv.conf and echo "nameserver 8.8.4.4 >> /etc/resolv.conf"

**Comment by zhj-buffer** [comment]
There is a bug in current deb release. So it will be failed and hang just after fecthed the deb package.
Pls try to compile the quem with source code to fix this issue.
I just verified with qeum 5.0, it works fine.
