### ISSUE TITLE
Error while executing "bash ch-mount.sh -m rootfs-nano"

### ISSUE THREAD

**Issue by mahimamrydotinfotech** [zhj-buffer/Cross-Compile-Jetson#6]
mount: mount point rootfs-nanoproc does not exist
mount: mount point rootfs-nanosys does not exist
mount: mount point rootfs-nanodev does not exist
mount: mount point rootfs-nanorun does not exist
chroot: cannot change root directory to 'rootfs-nano': No such file or directory

**Comment by yosoufe** [comment]
try `bash ch-mount.sh -m rootfs-nano/`. the difference is `/` at the end.

**Comment by zhj-buffer** [comment]
Pls refer to the previous ops to prepare the rootfs first.
